---
title: ""
output: html_document
---
##### For offline computation, analysis, and visualization, see the Bioconductor R package [*GRmetrics*](https://bioconductor.org/packages/GRmetrics).


### Step-by-Step Example

For a step-by-step example of using the GRcalculator, see [*here*](example.html).

###Instructions

To calculate normalized growth rate inhibition (GR) values and corresponding GR metrics: *GR~50~*, *GEC~50~*, *GR~max~*, *GR~inf~*, *GR~AOC~*, and *h~GR~* based on cell counts measured in dose-response experiments using this online tool, users must provide a data file in which each row represents a separate treatment condition and the columns specify the keys (variables) that define the treatment condition (e.g. cell line, drug or other perturbagen, perturbagen concentration, treatment time, replicate) and the measured cell counts (or surrogate such as CellTiter-Glo® or other readout). Analogous traditional metrics: *IC~50~*, *EC~50~*, *E~max~*, *E~inf~*, *AUC*, and *h* are also computed. Interactive analysis and visualization tools are provided. Detailed instructions can be found below.

####Step 1: Load the data file containing cell counts for treated and control cells.

GRcalculator accepts comma-separated (.csv) or tab-separated (.tsv) input files. It can also accept files that use commas as decimal points.

The input files can come in one of two different formats, here called "Case A" and "Case C". Case A is the simplest format, with treated and control cell counts in different columns. Case C is more general and has treated and control cell counts in the same column. See below for exact descriptions of Case A and Case C.

Click **Load Example Case A** or **Load Example Case C** to the left to view a sample data file in the *Data Tables* tab.

####Step 2: Select the grouping variables.
 
The key variables selected define on which variables the GR values will be averaged before fitting of the dose-response curves. By default, all variables are pre-selected, but, for example, replicates can be averaged by deselecting the proper column header. To deselect a variable, click on it in the grouping variables box and then press the "delete" or "backspace" key. You may repeat this with as many variables as you like.

####Step 3: Select additional options and click "Analyze"

Additionally, the user may select **Advanced options** and choose **Cap GR values below 1** and/or **Force sigmoidal fit**. If **Cap GR values below 1** is selected, all calculated GR values that are greater than 1 will be set to 1. If **Force sigmoidal fit** is selected, the calculator will attempt to "force" a sigmoidal rather than a straight line fit, i.e. it will allow for sigmoidal fits with F-test p-values greater than .05.

# {.tabset .tabset-fade .tabset-pills}
## Case A
####Case A: a single file with control values assigned to treated measurements
 
The input file(s) must have the following column headers (first row of the file):

1. **concentration** = concentration values (not log transformed) of the perturbagen on which dose-response curves will be evaluated
2. **cell_count** = measure of cell number (or a surrogate of cell number such as CellTiter-Glo® staining) after treatment
3. **cell_count\_\_time0** - initial (Time 0) cell counts - the measure of cell number in untreated wells grown in parallel until the time of treatment
4. **cell_count\_\_ctrl** - column with the Control cell count: the measure of cell number in control (e.g. untreated or DMSO-treated) wells from the same plate

All other columns will be treated as additional keys on which the data will be 
grouped (e.g. *cell_line*, *drug*, *time*, *replicate*)

## Case C
####Case C: a single file with control values stacked with treated measurements

In the most general case, the control cell counts are in the same file and 
format as the treated cell counts. Control cell counts will be averaged (using 
a 50%-trimmed mean) and automatically matched to the treated cell counts based 
on the keys (columns in the data file). The control cell count values must 
have a value of 0 for *concentration* and a value for *time* that matches the 
treated measurements. The time 0 cell count values must have value of 0 for 
*time*. If the structure of the data is complex, users should 
format their data as described in Case A as the underlying scripts may 
inappropriately match control and treated cell counts.

The input file(s) must have the following column headers (first row of the file):

1. **concentration** - column with concentration values (not log transformed) of the perturbagen on which dose-response curves will be evaluated
2. **cell_count** - column with the measure of cell number (or a surrogate of cell number such as CellTiter-Glo® staining)
3. **time** - column with the time at which a cell count is observed

All other columns will be treated as additional keys on which the data will be 
grouped (e.g. *cell_line*, *drug*, *replicate*)

